### ISSUE TITLE
Implement a new WN-Fn mapping

### ISSUE THREAD

**Issue by valeriobasile** [valeriobasile/learningbyreading#1]
Framester (https://github.com/framester/Framester) provides a better (?) coverage and accuracy of mapping between BabelNet , WordNet 3.0 and FrameNet than the one implemented now in KNEWS. 

BN-WN3.0:
https://github.com/framester/Framester/blob/master/fn-babelnet-mappings/bn-synsets-senses.ttl

BN-FN:
https://github.com/framester/Framester/blob/master/fn-babelnet-mappings/fn2bnFrameBase.ttl

Implement this mapping and clean the 'resource' directory.

**Comment by roquelopez** [comment]
In general, Knews mappings offer a slightly better coverage. See more details in this [page](https://github.com/valeriobasile/learningbyreading/wiki/Mappings-Comparison/).

**Comment by valeriobasile** [comment]
OK but what about the quality of the mapping? Any example where the old mapping is better than Framester?

**Comment by roquelopez** [comment]
In qualitative terms,  apparently the results are equivalent. Looking the outputs of these mappings, frames have similar structures (elements and roles). 
So, talking in terms of recall/coverage and precision,  apparently Knews mappings offer a slightly better coverage than Framester but their precisions are equivalents. 

See the following outputs for three frames:

**Knews**
<http://framebase.org/ns/frame-Commerce_buy-buy.v>
<http://framebase.org/ns/fe-Buyer>
<http://framebase.org/ns/fe-Goods>

<http://framebase.org/ns/frame-Attack-lay.v> .
<http://framebase.org/ns/fe-Assailant>
<http://framebase.org/ns/fe-Victim>

<http://framebase.org/ns/frame-Being_named-move.v>
<http://framebase.org/ns/fe-Speaker>
<http://framebase.org/ns/fe-Entity>


**Framester**
<http://framebase.org/ns/frame-Commerce_buy-buy.v>
<http://framebase.org/ns/fe-Buyer>
<http://framebase.org/ns/fe-Goods>

<http://framebase.org/ns/frame-Attack-lay.v>
<http://framebase.org/ns/fe-Assailant>
<http://framebase.org/ns/fe-Victim>

<http://framebase.org/ns/frame-Being_named-move.v>
<http://framebase.org/ns/fe-Speaker> 
<http://framebase.org/ns/fe-Entity>

**Comment by valeriobasile** [comment]
OK, can you leave the two mappings possible by switching a command line flag? Then we can close the issue and leave the qualitative evaluation for later.

**Comment by roquelopez** [comment]
I putted the option of choosing the mappings through a config file, similar to the case of selecting UKB or Babelfy. But of course, i can put it as command line parameter.

**Comment by valeriobasile** [comment]
It's good like that, thanks.
