### ISSUE TITLE
Tokenizer -> ERROR: length/2: Type error: `list' expected, found `"can"' (a string)

### ISSUE THREAD

**Issue by prpfialho** [valeriobasile/learningbyreading#13]
Hi,

I got the following error:

ERROR:root:Tokenizer error: 
ERROR: Prolog initialisation failed:
ERROR: length/2: Type error: `list' expected, found `"can"' (a string)

upon using:
tokens = tokenize("A woman jumps and poses for the camera.")
or
$ /bin/t

where:

$ make bin/t
$ make: 'bin/t' is up to date.

**Comment by valeriobasile** [comment]
It is weird that bin/t works out of the box for other users, but this may be due to the new versions of SWI Prolog not being compatible with Boxer (or better, the other way around). I saw your fix and pull request, I will just check if it all works in a fresh installation and then merge.

**Comment by valeriobasile** [comment]
Sorry I could not merge the pull request (see the note in the pull request itself).

I'll leave the issue open though, it something that needs to be fixed. A workaround is to install an older version of SWI prolog, 6.6.6 works: http://www.swi-prolog.org/download/stable/src/pl-6.6.6.tar.gz
