### ISSUE TITLE
unable to make soap

### ISSUE THREAD

**Issue by prpfialho** [valeriobasile/learningbyreading#16]
Hello,

I downloaded the current master verison of this project, and followed all the install instructions (boxer.conf is missing on the current repository, but I had a copy from a previous version).

The script install_candc.sh failed on "make soap", as:

> make soap
src/scripts/version unix
grep: directory: No such file or directory
g++ -W -Wall -Wextra -fPIC -O3 -Isrc/include -isystem ext/include   -c -o src/lib/version.o src/lib/version.cc
g++ -fPIC -o bin/soap_server src/lib/candc.o src/api/soap/soapC.o src/api/soap/soapServer.o src/api/soap/server.o src/lib/base.o src/lib/ports/unix.o src/lib/ports/unix_common.o src/lib/ports/colour.o src/lib/timer.o src/lib/input.o src/lib/word.o src/lib/version.o src/lib/licence.o src/lib/tagset.o src/lib/lexicon.o src/lib/utils/escape.o src/lib/config/node.o src/lib/config/option.o src/lib/config/config.o src/lib/io/format.o src/lib/io/stream.o src/lib/io/reader.o src/lib/io/reader_group.o src/lib/io/reader_horiz.o src/lib/io/reader_multi_horiz.o src/lib/io/reader_factory.o src/lib/io/writer.o src/lib/io/writer_stream.o src/lib/io/writer_group.o src/lib/io/writer_horiz.o src/lib/io/writer_multi_horiz.o src/lib/io/writer_vert.o src/lib/io/writer_multi_vert.o src/lib/io/writer_format.o src/lib/io/writer_factory.o src/lib/tagger/tagdict.o src/lib/tagger/tagsetdict.o src/lib/tagger/_baseimpl.o src/lib/tagger/tagger.o src/lib/tagger/taghist.o src/lib/model/types.o src/lib/model/registry.o src/lib/model/affix.o src/lib/model/unigram.o src/lib/model/bigram.o src/lib/model/trigram.o src/lib/model/model.o src/lib/model/cache.o src/lib/gazetteers.o src/lib/tagger/unigram.o src/lib/parser/atom.o src/lib/parser/feature.o src/lib/parser/varid.o src/lib/parser/category.o src/lib/parser/markedup.o src/lib/parser/categories.o src/lib/parser/gr.o src/lib/parser/gr_constraints.o src/lib/parser/relations.o src/lib/parser/supercat.o src/lib/parser/equiv.o src/lib/parser/chart.o src/lib/parser/unify.o src/lib/parser/treebank.o src/lib/parser/variable.o src/lib/parser/rule.o src/lib/tree/catvalue.o src/lib/tree/dependency.o src/lib/tree/distance.o src/lib/tree/rule.o src/lib/tree/depdist.o src/lib/tree/genrule.o src/lib/parser/rule_instances.o src/lib/parser/parser.o src/lib/parser/depscore.o src/lib/parser/canonical.o src/lib/parser/generator.o src/lib/parser/constraint.o src/lib/parser/print_deps.o src/lib/parser/print_prolog.o src/lib/parser/print_boxer.o src/lib/parser/print_ccgbank.o src/lib/parser/print_grs.o src/lib/parser/print_xml.o src/lib/parser/print_debug.o src/lib/parser/print_js.o src/lib/parser/print_latex.o src/lib/parser/print_factory.o src/lib/parser/decoder.o src/lib/parser/decoder_derivs.o src/lib/parser/decoder_derivs_random.o src/lib/parser/decoder_deps_recall.o src/lib/parser/decoder_factory.o src/lib/parser/beam.o src/lib/parser/count_rules.o src/lib/parser/print_forest.o src/lib/parser/inside_outside.o src/lib/parser/feature_root.o src/lib/parser/feature_rule.o src/lib/parser/feature_rule_head.o src/lib/parser/feature_dep.o src/lib/parser/feature_dep_dist.o src/lib/parser/feature_rule_dep.o src/lib/parser/feature_rule_dep_dist.o src/lib/parser/feature_genrule.o src/lib/parser/integration.o src/lib/tagger/pos.o src/lib/tagger/chunk.o src/lib/tagger/ner.o src/lib/tagger/super.o src/lib/relations/morpha.o src/lib/cluster_no_mpi.o -Llib -lm -Lext/lib -lgsoap++
src/api/soap/server.o: In function `run_server(std::string const&, std::string const&)':
server.cc:(.text+0x32be): undefined reference to `soap_init_LIBRARY_VERSION_REQUIRED_20816'
collect2: error: ld returned 1 exit status
Makefile.targets:696: recipe for target 'bin/soap_server' failed
make: *** [bin/soap_server] Error 1

Do you know what could be wrong?

I'm using openSUSE Leap 42.2.

Sincerely,
Pedro

**Comment by valeriobasile** [comment]
Hi Pedro,
  firstly, boxer.conf has been replaced by semanticparsing.conf, because I'm trying to make the semantic parsing module independent from Boxer only and give the option to use Semafor instead.

As for your SOAP question, I'm not sure what is going on there, as it's an external library that I just put into the repository to be safe against updates that could break backward compatibility. If you open the install_candc.sh script, you can see that it's pretty straightforward. Have you tried to execute it line by line? The make/make install on line 11-12 in particular, do they terminate correctly?

The "make soap" at the end compiles the SOAP client and server executables of the C&C tools pipeline. If gsoap is not correctly installed, that could be one reason to fail.

V.
