### ISSUE TITLE
Online postagging is not implemented for C&C/Boxer

### ISSUE THREAD

**Issue by Remper** [valeriobasile/learningbyreading#19]
https://github.com/valeriobasile/learningbyreading/blob/99835112fe0973fe309fbae38a21fa7ab1adce77/src/candc.py#L38

**Comment by valeriobasile** [comment]
Fixed by this commit: https://github.com/valeriobasile/learningbyreading/commit/bd9edd2094b6ce47b66f6c39d19771b3fa162e03
