### ISSUE TITLE
make DRS for a txt data file?

### ISSUE THREAD

**Issue by shankha117** [valeriobasile/learningbyreading#21]
I am trying out a sentence simplification mode.
How do I use the API to generate a Boxer DRS output in XML format from a .txt file. 
.txt file is my corpus data of complex sentence.

**Comment by valeriobasile** [comment]
Boxer is an external component of KNEWS, and it has been replaced by Semafor, although it is still possible to configure KNEWS to run SRL with Boxer.
There should be a command line flag of Boxer to get XML output ("--format xml" or something like that). Please check the Boxer documentation, or its command line help. Do not report issues with Boxer here, this is the KNEWS repository.
