### ISSUE TITLE
Boxer errors

### ISSUE THREAD

**Issue by Crista23** [valeriobasile/learningbyreading#25]
Thank you for sharing Boxer. As I am trying to use it as part of Hybrid following the directions [here](https://github.com/shashiongithub/Sentence-Simplification-ACL14/issues/2), my output is as follows:

bin/candc --input test.txt --models models/boxer > test.ccg
 this file was generated by the following command(s):
   bin/candc --input /srv/disk01/ggarbace/TS/dataset/zhu_acl2010/test.txt --models models/boxer

1 parsed at B=0.075, K=20
1 coverage 100%
1 stats 10.8077 1479 2488 comb 2300 1438 0 0

bin/boxer --input test.ccg --semantics drs --output test.out --resolve true --instantiate true --format xml --elimeq true

ERROR: test.ccg:24: Syntax error: Undefined character escape in quoted atom or string: `\N'
ERROR: test.ccg:27: Syntax error: Undefined character escape in quoted atom or string: `\('

If I replace \N with \\N and \( with \\( and run the command again, what I get is:

ERROR: unable to preprocess derivation 1

Can you please let me know what I am doing wrong here? How can I get Boxer to work? Thank you!

**Comment by valeriobasile** [comment]
Sorry, this is not a repository for Boxer, I am not a developer of Boxer and I may not be able to answer these questions.
As a user, it seems to me that the call to bin/candc is missing the "--candc-printer boxer" argument. This should be the last argument on the command line and changes the output format of bin/candc to a format that Boxer digests.
